### ISSUE TITLE
AWS 환경 세팅

### ISSUE THREAD

**Issue by luke0408** [GC-Project-Space/Algo_TEAM-6_back#2]
## 설명
> develop 배포 환경 세팅

## To-do
- [x] AWS 환경 구축
  - [x] EC2 세팅: nginx
  - [x] RDS 세팅: mysql
  - [x] S3 세팅
- [x] local 환경 적용
